#!/bin/bash

file=/var/log/update_script.log

date >> $file
echo '--- SOURCES - apt-get update -----' >> $file
apt-get update >> $file
echo '--- PACKAGES - apt-get upgrade ---' >> $file
apt-get upgrade >> $file
echo >> $file
