#!/bin/bash

file=/var/log/update_script.log

date >> $file 2>&1
echo '--- SOURCES - apt-get update -----' >> $file 2>&1
apt-get update >> $file 2>&1
echo '--- PACKAGES - apt-get upgrade ---' >> $file 2>&1
apt-get upgrade >> $file 2>&1
echo >> $file 2>&1

# to execute in root

# add cron (as root)
# crontab -e
# add line : 0 4 * * 5 /home/curquiza/Documents/init/scripts/02
# (every friday)
